### ISSUE TITLE
Support for filtration algos

### ISSUE THREAD

**Issue by gtauzin** [giotto-ai/pyflagser#16]
#### Description
Right now, we only support the default filtration algorithm. However, flagser incudes a number of ways to compute filtration from edges and vertices weights. It can even allow the user to build its own filtration function.

**Comment by gtauzin** [comment]
@MonkeyBreaker I will take care of it and ask for your review!

**Comment by ulupo** [comment]
Closing as this was addressed by #18 (minus the custom filtration functions).
