### ISSUE TITLE
Computations take a long time

### ISSUE THREAD

**Issue by wreise** [giotto-ai/pyflagser#17]
#### Description
I am not aware of how long the computations wth flagser should take, but it seems like the example in #15 takes more than a few minutes ( actually, it did not terminate on my machine).

#### Steps/Code to Reproduce
Follow step 1. in #15.

#### Expected Results
Computation terminates in a few minutes for a distance matrix of size`50x50`.

#### Actual Results
Does not terminate in 15 minutes.

#### Versions
Darwin-19.3.0-x86_64-i386-64bit
Python 3.7.6 (default, Dec 30 2019, 19:38:26) 
[Clang 11.0.0 (clang-1100.0.33.16)]
pyflagser 0.1.0

**Comment by wreise** [comment]
I am no longer experiencing this issue since 0.2.0.

**Comment by MonkeyBreaker** [comment]
Okay, this was resolved by #21, the problem was that setting min, max dimension was not setting as expected the arguments.
