### ISSUE TITLE
Missing features from flagser binding

### ISSUE THREAD

**Issue by reds-heig** [giotto-ai/pyflagser#2]
#### Description

The first version of the bindings for `flagser` is done in #1. The current python Interface does not support all the possible features described in [flagser docs](https://github.com/luetge/flagser/blob/master/docs/documentation_flagser.pdf).

The following to-do list report the current status of the missing features (the list is not sorted by priority):

- [x] max-dim support: the maximal homology dimension to be computed
- [x] min-dim dim: the minimal homology dimension to be computed
- [x] approximate n: skip all cells creating columns in the reduction matrix with more than n entries. Use this for hard problems, a good value is often 100000. Increase for higher precision, decrease for faster computation. Warning: for non-trivial filtrations, this makes for hard to estimate theoretical bounds on the error, although usually the real error is much lower than the theoretical one. Use for exploration and validate later with longer computation time
- [ ] components: compute the directed flag complex for each individual connected component of the input graph. Warning: this currently only works for the trivial filtration. Additionally, this ignores all isolated vertices.
- [x] undirected: computes the undirected flag complex instead
- [ ] h5 support ? Is it necessary if we eventually implement to pass directly the data to `flagser` ?
- [ ] Defining a filtration algorithm, I personally did not fully understand this section.
- [x] modulus or coeff (called in python code)

Other useful improvement could be:

- [x] instead of passing a file to `flagser` directly give him the data. This allow to not store any data on disk.
- [ ] Because of the implementation of `flagser`, it needs to write a file on disk. we'll need to check with the maintainer of `flagser` to update this behavior and not make this a requirement. Because I need to manage the writing of the file in the python bindings.

This list shall be updated when features are implement and if other missing features should be added.

Regards,
Julián

**Comment by gtauzin** [comment]
Hi Julián,

As of now, I think the priority for the python bindings as well as for the giotto-learn library would be to get rid of the need to go through writing a file on the disk. 

For now, I would suggest to have max and min dim, approximate n and undirected support in that order.

Defining a filtration algorithm is more convoluted and we won't need it in the near future.

Thanks!

**Comment by gtauzin** [comment]
Hi @MonkeyBreaker,

The library is almost ready and I have added support for "modulus" called coeff in the python code.

Would you mind adding support for max and min dim?

**Comment by reds-heig** [comment]
In my opinion yes, not as I would like to do it (settings in python, then uses settings in c++).
What it'll currently do is settings in python and then in cpp transform them as parameters and convert them to arguments.

By the end of the week I should be ready with this, is it good for you ?

**Comment by gtauzin** [comment]
Yes, I have seen it, I think that's fine for now.

End of the week would be nice, thanks! I think the biggest issue to the release is the windows compatibility described in #4, that would be slightly more pressing.

**Comment by gtauzin** [comment]
I will close it for now. I think the features present are sufficient. Do not hesitate to open a new issue to request new features.
