### ISSUE TITLE
Filtration algorithm vertex_degree produces segmentation fault

### ISSUE THREAD

**Issue by MonkeyBreaker** [giotto-ai/pyflagser#22]
#### Description

PR #21 Added test for different filtrations. But testing algorithm `vertex_degree` produced segmentation fault with dataset `d5.flag`.

#### Steps/Code to Reproduce

```python
import 
flag_matrix = loadflag('flagser/test/d5.flag')
res = flagser(flag_matrix, max_dimension=1, directed=False, filtration='vertex_degree')
```

#### Expected Results

Results of filtration, but in general no segmentation fault.

#### Actual Results

```bash
segmentation fault (core dumped)
```
#### Versions

Version `0.2.0`

**Comment by ulupo** [comment]
@MonkeyBreaker close this?

**Comment by MonkeyBreaker** [comment]
Yes !
