### ISSUE TITLE
Drop support for Python 3.6

### ISSUE THREAD

**Issue by ulupo** [giotto-ai/pyflagser#72]
We should probably drop support for Python 3.6, as `scikit-learn` decided to do recently: https://github.com/scikit-learn/scikit-learn/issues/20084.  This would also make the CI a lot leaner and faster to run.

**Comment by ulupo** [comment]
@MonkeyBreaker , if you agree, we can fix this as part of #70 .

**Comment by MonkeyBreaker** [comment]
Hard to say if `Python3.6` is old enough to drop support to it.
We can drop support to it, but I don't think in this specific case we should drop support to `Python3.6`.

BTW, on my machine I still use Python 3.6 ...

**Comment by MonkeyBreaker** [comment]
As it is mentioned in the issue you shared if we drop support to Python3.6 we need to maybe update the minimal versions of Python packages we use (NumPy and SciPy).

**Comment by ulupo** [comment]
I think the reasons for dropping support would be the same as for scikit-learn -- no updates since 2018, simpler CI.  I think our minimal versions are recent enough but I'll check.

**Comment by MonkeyBreaker** [comment]
Then let's go :D !
If you can confirm the requirements version, I update #70 and we will drop officially support to Python 3.6.
We need to not forget to update the documentation README, doc/

**Comment by MonkeyBreaker** [comment]
Fixed by #70
